on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: lts/*

      - name: build clrc
        run: |
          npm install
          npm run build

      - name: build playground and deploy to pages
        run: |
          cd playground

          npm install
          npm run build
          cd build

          git init
          git config --local user.name mebtte
          git config --local user.email hi@mebtte.com
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git switch -c gh-pages
          git add -A
          git commit -m "auto deploy"
          git push origin gh-pages -f
